### ISSUE TITLE
Decide XML library to use

### ISSUE THREAD

**Issue by lauraluiz** [sphereio/sphere-lightspeed-onsite-connector#3]
LS uses XML to communicate.

**Comment by schleichardt** [comment]
I suggest this one: https://github.com/FasterXML/jackson-dataformat-xml/wiki

**Comment by lauraluiz** [comment]
Yes, I was testing this one right now :)

**Comment by lauraluiz** [comment]
So far it looks good. I had to deal with some minor problems, but made it work. It is a bit strange so far that some nomenclature mentions JSON instead of XML, but that's nothing that worries me.
